(function (root) {
  function deepFreeze(value) {
    if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
    Object.freeze(value);
    for (const key of Object.keys(value)) {
      deepFreeze(value[key]);
    }
    return value;
  }

  const ACTIVITY_CONTENT = {
    version: 1,
    campaignOrder: ['brian', 'jake'],
    shared: {
      gambling: {
        unlockCopy: 'Open the backroom once Jake learns the city has a price on everything.',
        purpose: 'Convert spare currency into risk, spikes, and rare comeback power.',
        currencies: ['chips', 'tickets', 'marks'],
        slots: {
          unlockCopy: 'A neon cabinet with loud reels and a quiet edge.',
          rewardStyle: 'Burst rewards with streak multipliers and jackpot spikes.',
          tiers: [
            {
              id: 'slots_dive_bar',
              name: 'Dive Bar Slots',
              unlockCopy: 'The first machine is broken in a way that still pays.',
              stakeTier: 1,
              volatility: 'low',
              reward: { chips: [10, 40], tickets: [0, 1], marks: [0, 0] },
              jackpots: [
                { id: 'small_flush', name: 'Small Flush', multiplier: 3, unlockCopy: 'Three reels line up and the bartender stops talking.' },
                { id: 'neon_shower', name: 'Neon Shower', multiplier: 6, unlockCopy: 'The cabinet spits coins like it is annoyed to be winning.' },
              ],
            },
            {
              id: 'slots_city_line',
              name: 'City Line Slots',
              unlockCopy: 'The machine gets smarter and the payouts get meaner.',
              stakeTier: 2,
              volatility: 'medium',
              reward: { chips: [35, 120], tickets: [1, 2], marks: [0, 1] },
              jackpots: [
                { id: 'double_orbit', name: 'Double Orbit', multiplier: 5, unlockCopy: 'The lights blur into one clean streak.' },
                { id: 'stacked_crown', name: 'Stacked Crown', multiplier: 10, unlockCopy: 'The crown lands twice. Everyone hears it.' },
              ],
            },
            {
              id: 'slots_backroom_royal',
              name: 'Backroom Royal',
              unlockCopy: 'Reserved for the players who already broke even twice.',
              stakeTier: 3,
              volatility: 'high',
              reward: { chips: [80, 320], tickets: [2, 4], marks: [1, 2] },
              jackpots: [
                { id: 'midnight_king', name: 'Midnight King', multiplier: 12, unlockCopy: 'The room goes silent before the payout hits.' },
                { id: 'zero_to_legend', name: 'Zero to Legend', multiplier: 20, unlockCopy: 'A single spin changes the whole room.' },
              ],
            },
            {
              id: 'slots_last_call',
              name: 'Last Call Vault',
              unlockCopy: 'The final machine only opens if the player already knows the odds are fake.',
              stakeTier: 4,
              volatility: 'extreme',
              reward: { chips: [200, 1000], tickets: [4, 8], marks: [2, 4] },
              jackpots: [
                { id: 'golden_exit', name: 'Golden Exit', multiplier: 30, unlockCopy: 'The reels stop on the exact image you needed.' },
                { id: 'mythic_run', name: 'Mythic Run', multiplier: 50, unlockCopy: 'The vault pays out like it remembers your name.' },
              ],
            },
          ],
        },
        blackjack: {
          unlockCopy: 'The table in the corner is always one hand away from disaster.',
          rewardStyle: 'Controlled risk, score pushes, and soft counterplay bonuses.',
          tables: [
            {
              id: 'table_side_room',
              name: 'Side Room Table',
              unlockCopy: 'Low stakes, fast lessons.',
              minBet: 5,
              maxBet: 25,
              dealerBias: 'soft',
              reward: { chips: [15, 60], tickets: [0, 1], marks: [0, 0] },
            },
            {
              id: 'table_back_door',
              name: 'Back Door Table',
              unlockCopy: 'The dealer is polite enough to be dangerous.',
              minBet: 20,
              maxBet: 100,
              dealerBias: 'balanced',
              reward: { chips: [50, 180], tickets: [1, 2], marks: [0, 1] },
            },
            {
              id: 'table_owners_club',
              name: 'Owners Club Table',
              unlockCopy: 'The house smiles when the stakes get uncomfortable.',
              minBet: 75,
              maxBet: 500,
              dealerBias: 'aggressive',
              reward: { chips: [140, 480], tickets: [2, 4], marks: [1, 2] },
            },
          ],
          sideBets: [
            { id: 'perfect_pair', name: 'Perfect Pair', unlockCopy: 'Two cards, one impossible mood.', reward: { chips: 25, marks: 1 } },
            { id: 'dealer_bust', name: 'Dealer Bust', unlockCopy: 'Bet on the room making a mistake.', reward: { chips: 40, marks: 1 } },
            { id: 'five_card_charlie', name: 'Five Card Charlie', unlockCopy: 'Chase the hand nobody expects.', reward: { chips: 60, tickets: 1 } },
            { id: 'insurance_flip', name: 'Insurance Flip', unlockCopy: 'The safest bet is still a bet.', reward: { chips: 80, marks: 2 } },
          ],
        },
        dice: {
          unlockCopy: 'A pair of dice, a cup, and a crowd that likes pressure.',
          rewardStyle: 'Fast resolution, swingy payouts, and streak-driven momentum.',
          games: [
            {
              id: 'street_ones',
              name: 'Street Ones',
              unlockCopy: 'Simple odds for simple cash.',
              dice: 2,
              targetBands: ['snake eyes', 'high total'],
              reward: { chips: [8, 35], tickets: [0, 1], marks: [0, 0] },
            },
            {
              id: 'cup_run',
              name: 'Cup Run',
              unlockCopy: 'The cup shakes harder when the room is watching.',
              dice: 3,
              targetBands: ['triples', 'staircase', 'snake eyes'],
              reward: { chips: [20, 90], tickets: [1, 2], marks: [0, 1] },
            },
            {
              id: 'all_in_roll',
              name: 'All-In Roll',
              unlockCopy: 'This one exists for players who like the edge of a cliff.',
              dice: 5,
              targetBands: ['full house', 'clean run', 'legend roll'],
              reward: { chips: [60, 240], tickets: [2, 4], marks: [1, 3] },
            },
          ],
        },
      },
      autobattler: {
        unlockCopy: 'Recruit a squad when the city stops being a hallway and starts being a board.',
        purpose: 'Build a lineup, survive encounters, and cash out with layered rewards.',
        roster: [
          {
            id: 'unit_hustler',
            name: 'Hustler',
            role: 'scout',
            tier: 1,
            stats: { hp: 12, attack: 4, speed: 7 },
            synergy: ['street'],
            passive: 'Starts with a bonus on first strike.',
            unlockCopy: 'A quick starter that wins by moving first.',
          },
          {
            id: 'unit_brawler',
            name: 'Brawler',
            role: 'frontline',
            tier: 1,
            stats: { hp: 18, attack: 5, speed: 4 },
            synergy: ['bruiser'],
            passive: 'Takes a hit and stays standing.',
            unlockCopy: 'Cheap armor with a hard punch.',
          },
          {
            id: 'unit_fixer',
            name: 'Fixer',
            role: 'support',
            tier: 2,
            stats: { hp: 14, attack: 3, speed: 6 },
            synergy: ['street', 'control'],
            passive: 'Heals the ally that looks closest to losing.',
            unlockCopy: 'Keeps the crew from unraveling.',
          },
          {
            id: 'unit_analyst',
            name: 'Analyst',
            role: 'buffer',
            tier: 2,
            stats: { hp: 11, attack: 4, speed: 5 },
            synergy: ['control', 'economy'],
            passive: 'Boosts the team after every win.',
            unlockCopy: 'Sees the whole table before the fight starts.',
          },
          {
            id: 'unit_scavenger',
            name: 'Scavenger',
            role: 'economy',
            tier: 2,
            stats: { hp: 13, attack: 3, speed: 5 },
            synergy: ['economy'],
            passive: 'Drops extra loot if the round ends early.',
            unlockCopy: 'Turns leftovers into momentum.',
          },
          {
            id: 'unit_brute',
            name: 'Brute',
            role: 'frontline',
            tier: 3,
            stats: { hp: 28, attack: 8, speed: 3 },
            synergy: ['bruiser'],
            passive: 'Punishes enemies when it survives a round.',
            unlockCopy: 'Heavy enough to bend a battle plan.',
          },
          {
            id: 'unit_duo',
            name: 'Duo Act',
            role: 'combo',
            tier: 3,
            stats: { hp: 16, attack: 7, speed: 8 },
            synergy: ['street', 'control'],
            passive: 'Acts twice if the enemy team has fewer units.',
            unlockCopy: 'Two people, one problem.',
          },
          {
            id: 'unit_bookie',
            name: 'Bookie',
            role: 'economy',
            tier: 3,
            stats: { hp: 15, attack: 4, speed: 5 },
            synergy: ['economy', 'control'],
            passive: 'Converts win streaks into chips.',
            unlockCopy: 'Knows the odds and sells them back to you.',
          },
          {
            id: 'unit_shadow',
            name: 'Shadow',
            role: 'assassin',
            tier: 4,
            stats: { hp: 12, attack: 11, speed: 10 },
            synergy: ['control', 'bruiser'],
            passive: 'Targets the weakest enemy first.',
            unlockCopy: 'Blends into the edge of the board.',
          },
          {
            id: 'unit_ace',
            name: 'Ace',
            role: 'carry',
            tier: 4,
            stats: { hp: 20, attack: 12, speed: 7 },
            synergy: ['street', 'economy'],
            passive: 'Gets stronger when the squad has already won a few rounds.',
            unlockCopy: 'The kind of piece the whole table starts watching.',
          },
          {
            id: 'unit_guardian',
            name: 'Guardian',
            role: 'tank',
            tier: 4,
            stats: { hp: 34, attack: 6, speed: 2 },
            synergy: ['bruiser'],
            passive: 'Protects adjacent allies.',
            unlockCopy: 'A shield with a grudge.',
          },
          {
            id: 'unit_wildcard',
            name: 'Wildcard',
            role: 'flex',
            tier: 5,
            stats: { hp: 22, attack: 10, speed: 9 },
            synergy: ['street', 'economy', 'control'],
            passive: 'Copies the strongest trait on the board.',
            unlockCopy: 'Never sits still long enough to be measured.',
          },
        ],
        encounters: [
          {
            id: 'enc_warehouse_misfits',
            name: 'Warehouse Misfits',
            tier: 1,
            enemyTraits: ['street'],
            reward: { chips: 25, xp: 10, rerolls: 1, unlockCopy: 'You beat a crew that was mostly noise.' },
          },
          {
            id: 'enc_parking_lot_brawl',
            name: 'Parking Lot Brawl',
            tier: 1,
            enemyTraits: ['bruiser'],
            reward: { chips: 35, xp: 12, rerolls: 1, unlockCopy: 'First blood, first prize.' },
          },
          {
            id: 'enc_backroom_scouts',
            name: 'Backroom Scouts',
            tier: 2,
            enemyTraits: ['control', 'economy'],
            reward: { chips: 60, xp: 18, rerolls: 2, unlockCopy: 'The room was measuring you the whole time.' },
          },
          {
            id: 'enc_subway_strikers',
            name: 'Subway Strikers',
            tier: 2,
            enemyTraits: ['street', 'assassin'],
            reward: { chips: 80, xp: 22, rerolls: 2, unlockCopy: 'The line to the train became a line to the prize.' },
          },
          {
            id: 'enc_motel_gang',
            name: 'Motel Gang',
            tier: 3,
            enemyTraits: ['bruiser', 'control'],
            reward: { chips: 120, xp: 28, rerolls: 3, unlockCopy: 'You took the lobby before they could settle in.' },
          },
          {
            id: 'enc_neon_ring',
            name: 'Neon Ring',
            tier: 3,
            enemyTraits: ['carry', 'economy'],
            reward: { chips: 160, xp: 35, rerolls: 3, unlockCopy: 'The lights were for show. The prize was real.' },
          },
          {
            id: 'enc_boss_the_fixer',
            name: 'Boss: The Fixer',
            tier: 4,
            enemyTraits: ['support', 'control'],
            reward: { chips: 260, xp: 48, rerolls: 4, unlockCopy: 'The boss came with a ledger and a smile.' },
          },
          {
            id: 'enc_boss_boardroom_blitz',
            name: 'Boss: Boardroom Blitz',
            tier: 4,
            enemyTraits: ['bruiser', 'economy', 'carry'],
            reward: { chips: 340, xp: 60, rerolls: 5, unlockCopy: 'When the board starts fighting, the whole city feels it.' },
          },
          {
            id: 'enc_boss_mirror_jake',
            name: 'Boss: Mirror Jake',
            tier: 5,
            enemyTraits: ['flex', 'assassin', 'carry'],
            reward: { chips: 500, xp: 80, rerolls: 6, unlockCopy: 'The hardest fight is usually the one that looks back.' },
          },
        ],
        rewards: [
          { id: 'reward_cash_drop', name: 'Cash Drop', unlockCopy: 'A clean payout with no strings attached.', effect: { chips: 100, tickets: 1 } },
          { id: 'reward_token_cache', name: 'Token Cache', unlockCopy: 'Enough chips to keep the table warm.', effect: { chips: 180, rerolls: 1 } },
          { id: 'reward_mod_chip', name: 'Mod Chip', unlockCopy: 'Lets one unit keep its edge between fights.', effect: { xp: 20, item: 'mod_chip' } },
          { id: 'reward_brink_bonus', name: 'Brink Bonus', unlockCopy: 'Winning on the edge should pay better.', effect: { chips: 300, marks: 2 } },
          { id: 'reward_crew_ticket', name: 'Crew Ticket', unlockCopy: 'One more body, one more line of play.', effect: { rerolls: 2, recruit: 1 } },
          { id: 'reward_champion_key', name: 'Champion Key', unlockCopy: 'Opens the final bracket.', effect: { unlock: 'champion_bracket', marks: 3 } },
        ],
        mutators: [
          { id: 'mutator_slow_cash', name: 'Slow Cash', unlockCopy: 'Rewards arrive later but hit harder.', modifier: { payoutDelay: 1.25, rewardMult: 1.15 } },
          { id: 'mutator_double_or_nothing', name: 'Double or Nothing', unlockCopy: 'Every win can become a spike.', modifier: { rewardMult: 1.5, riskMult: 1.3 } },
          { id: 'mutator_clean_streak', name: 'Clean Streak', unlockCopy: 'Chain wins to unlock hidden rewards.', modifier: { streakBonus: true } },
        ],
      },
      hustles: {
        unlockCopy: 'The city fills with side jobs once Jake learns how to read a room fast.',
        purpose: 'Provide low-ceremony, repeatable jobs that feed gambling, battler, and campaign progression.',
        tiers: [
          {
            id: 'hustle_neighborhood',
            name: 'Neighborhood',
            unlockCopy: 'Small errands, honest cash, fast turnover.',
            rewardMult: 1,
            riskMult: 0.8,
          },
          {
            id: 'hustle_district',
            name: 'District',
            unlockCopy: 'The jobs get longer and the payoff gets loud.',
            rewardMult: 1.75,
            riskMult: 1,
          },
          {
            id: 'hustle_city',
            name: 'City',
            unlockCopy: 'Now the jobs start touching real people with real leverage.',
            rewardMult: 2.75,
            riskMult: 1.15,
          },
          {
            id: 'hustle_night',
            name: 'Night Shift',
            unlockCopy: 'Only the serious players stay out this late.',
            rewardMult: 4,
            riskMult: 1.35,
          },
        ],
        jobs: [
          {
            id: 'job_pizza_dash',
            name: 'Pizza Dash',
            unlockCopy: 'Deliver before the crust goes cold.',
            tier: 'hustle_neighborhood',
            duration: 30,
            reward: { chips: [12, 30], reputation: [0, 1], items: ['hot_bag'] },
          },
          {
            id: 'job_parking_valet',
            name: 'Parking Valet',
            unlockCopy: 'Keep the keys moving and the night quiet.',
            tier: 'hustle_neighborhood',
            duration: 45,
            reward: { chips: [18, 42], reputation: [1, 2], items: ['key_ring'] },
          },
          {
            id: 'job_flyer_run',
            name: 'Flyer Run',
            unlockCopy: 'Paper in hand, boots on pavement.',
            tier: 'hustle_district',
            duration: 60,
            reward: { chips: [28, 60], reputation: [1, 3], items: ['street_map'] },
          },
          {
            id: 'job_loader_shift',
            name: 'Loader Shift',
            unlockCopy: 'Heavy boxes make fast money if nobody asks questions.',
            tier: 'hustle_district',
            duration: 90,
            reward: { chips: [45, 95], reputation: [2, 4], items: ['work_gloves'] },
          },
          {
            id: 'job_popup_bar',
            name: 'Popup Bar',
            unlockCopy: 'Pour, smile, repeat.',
            tier: 'hustle_city',
            duration: 120,
            reward: { chips: [70, 140], reputation: [3, 5], items: ['bar_tab'] },
          },
          {
            id: 'job_rooftop_install',
            name: 'Rooftop Install',
            unlockCopy: 'One bad step and the story changes.',
            tier: 'hustle_city',
            duration: 150,
            reward: { chips: [95, 180], reputation: [4, 6], items: ['toolkit'] },
          },
          {
            id: 'job_midnight_courier',
            name: 'Midnight Courier',
            unlockCopy: 'Nobody asks what is inside the envelope.',
            tier: 'hustle_night',
            duration: 180,
            reward: { chips: [140, 260], reputation: [5, 8], items: ['sealed_packet'] },
          },
          {
            id: 'job_cash_drop',
            name: 'Cash Drop',
            unlockCopy: 'Move the bag without drawing a breath.',
            tier: 'hustle_night',
            duration: 210,
            reward: { chips: [200, 360], reputation: [6, 10], items: ['black_bag'] },
          },
        ],
      },
    },
    campaigns: {
      brian: {
        name: 'Brian',
        finaleChoices: [
          {
            id: 'brian_stay',
            name: 'Stay Brian',
            unlockCopy: 'Keep the Brian run going with the shared expansion systems.',
            nextCampaign: 'brian_postgame',
          },
          {
            id: 'brian_become_jake',
            name: 'Become Jake',
            unlockCopy: 'Hand the baton to Jake and start a second full storyline.',
            nextCampaign: 'jake',
          },
        ],
        postgameSystems: ['gambling', 'autobattler', 'hustles'],
        expansionBeats: [
          {
            id: 'brian_backroom_open',
            phase: 5,
            unlockCopy: 'Brian finds the hidden venue under the city and realizes the game did not end. It expanded.',
            reward: 'Unlock shared gambling tables.',
          },
          {
            id: 'brian_crew_recruit',
            phase: 5,
            unlockCopy: 'Brian can now recruit a tactical crew for bracket fights and dice nights.',
            reward: 'Unlock the autobattler roster.',
          },
          {
            id: 'brian_side_jobs',
            phase: 5,
            unlockCopy: 'Even at the top, Brian can still take side work to keep the machine moving.',
            reward: 'Unlock hustle contracts.',
          },
        ],
      },
      jake: {
        name: 'Jake',
        introCopy: 'Jake starts where Brian leaves off: with leverage, a few enemies, and a city that respects momentum more than history.',
        switchCopy: 'Choose Jake when Brian finishes. The save continues, but the storyline changes tone and structure.',
        phaseNames: {
          1: 'Phase 1: Under the Radar',
          2: 'Phase 2: The Hustle',
          3: 'Phase 3: The Crew',
          4: 'Phase 4: The Machine',
          5: 'Phase 5: The Switch',
        },
        phaseSubtitles: {
          1: 'small moves, hidden edges',
          2: 'money in motion',
          3: 'people as infrastructure',
          4: 'systems that pay back',
          5: 'choose what the city remembers',
        },
        phaseIntro: [
          {
            phase: 1,
            unlockCopy: 'Jake starts small: side work, quiet bets, and a pocket full of maybe.',
            reward: 'Open hustle jobs and light-risk gambling.',
          },
          {
            phase: 2,
            unlockCopy: 'The backroom opens. Jake now has access to tables, dice, and the first proper crew fights.',
            reward: 'Open slots, blackjack, and the first autobattler bracket.',
          },
          {
            phase: 3,
            unlockCopy: 'Jake is no longer just earning. He is coordinating a machine that can win without him in the room.',
            reward: 'Unlock higher-stakes gambling and deeper squad synergies.',
          },
          {
            phase: 4,
            unlockCopy: 'The city starts paying Jake to stay organized.',
            reward: 'Unlock elite tables, higher bracket encounters, and premium hustle contracts.',
          },
          {
            phase: 5,
            unlockCopy: 'At the end, Jake chooses whether to absorb the city, walk away, or become the person who inherits both stories.',
            reward: 'Final branch choice and legacy ending.',
          },
        ],
        mechanics: {
          gambling: ['slots', 'blackjack', 'dice'],
          autobattler: ['roster', 'encounters', 'rewards', 'mutators'],
          hustles: ['jobs', 'tiers', 'streak bonuses'],
        },
        actions: {
          1: [
            { id: 'j1_scout', name: 'Scout the Block', unlockCopy: 'Learn the neighborhood pressure points.', energyCost: 1, reward: { chips: 1, intel: 1 } },
            { id: 'j1_favor', name: 'Cash a Favor', unlockCopy: 'Turn a past favor into current leverage.', energyCost: 2, reward: { chips: 3, reputation: 1 } },
            { id: 'j1_flip', name: 'Flip a Find', unlockCopy: 'Sell something before anyone notices it was missing.', energyCost: 2, reward: { chips: 5, marks: 1 } },
            { id: 'j1_line', name: 'Run a Quiet Line', unlockCopy: 'Move small volume without attention.', energyCost: 3, reward: { chips: 8, hustleXp: 1 } },
            { id: 'j1_watch', name: 'Watch the Corner', unlockCopy: 'The corner always tells you what is coming next.', energyCost: 1, reward: { intel: 2 } },
          ],
          2: [
            { id: 'j2_table', name: 'Sit the Table', unlockCopy: 'Jake gets his first honest look at house rules.', energyCost: 4, reward: { chips: 12, tableRep: 1 } },
            { id: 'j2_bet', name: 'Place a Smart Bet', unlockCopy: 'Risk with a reason is still risk.', energyCost: 3, reward: { chips: 10, marks: 1 } },
            { id: 'j2_recruit', name: 'Recruit a Driver', unlockCopy: 'A crew starts with somebody who can move things fast.', energyCost: 5, reward: { crew: 1, reputation: 1 } },
            { id: 'j2_scheme', name: 'Pitch a Scheme', unlockCopy: 'The city loves a plan as long as it sounds expensive.', energyCost: 5, reward: { chips: 18, scheme: 1 } },
            { id: 'j2_watchlist', name: 'Build a Watchlist', unlockCopy: 'Know who wins, who lies, and who pays late.', energyCost: 2, reward: { intel: 3 } },
          ],
          3: [
            { id: 'j3_open_book', name: 'Open the Book', unlockCopy: 'The book is only funny until it becomes yours.', energyCost: 5, reward: { chips: 24, book: 1 } },
            { id: 'j3_stack_team', name: 'Stack the Team', unlockCopy: 'Put the right bodies in the right order.', energyCost: 6, reward: { crew: 2, synergy: 1 } },
            { id: 'j3_press', name: 'Apply Pressure', unlockCopy: 'The room gives up when the room knows you can wait.', energyCost: 4, reward: { reputation: 3, marks: 1 } },
            { id: 'j3_split', name: 'Split the Difference', unlockCopy: 'Take the margin and let the other side think they won.', energyCost: 4, reward: { chips: 20, marks: 2 } },
            { id: 'j3_hold', name: 'Hold the Line', unlockCopy: 'Someone has to stand still so the machine can move.', energyCost: 3, reward: { crew: 1, stability: 1 } },
          ],
          4: [
            { id: 'j4_run_house', name: 'Run the House', unlockCopy: 'Jake stops playing the table and starts managing it.', energyCost: 6, reward: { chips: 40, house: 1 } },
            { id: 'j4_champion', name: 'Train a Champion', unlockCopy: 'One strong piece can carry an entire bracket.', energyCost: 7, reward: { battlerXp: 2, crew: 1 } },
            { id: 'j4_shuffle', name: 'Shuffle the Ledger', unlockCopy: 'Move the money where the city cannot count it.', energyCost: 5, reward: { chips: 32, marks: 3 } },
            { id: 'j4_bet_on_self', name: 'Bet on Yourself', unlockCopy: 'The best wager is usually the one with your own name on it.', energyCost: 4, reward: { chips: 28, confidence: 1 } },
            { id: 'j4_clear_heat', name: 'Clear the Heat', unlockCopy: 'You cannot scale if the pressure is sitting on your door.', energyCost: 4, reward: { heat: -1, intel: 2 } },
          ],
          5: [
            { id: 'j5_become_crown', name: 'Become the Crown', unlockCopy: 'Jake stops inheriting systems and starts defining them.', energyCost: 8, reward: { legacy: 1 } },
            { id: 'j5_take_exit', name: 'Take the Exit', unlockCopy: 'Walk away with the city still buzzing behind you.', energyCost: 6, reward: { ending: 'out', chips: 80 } },
            { id: 'j5_merge_stories', name: 'Merge the Stories', unlockCopy: 'Brian and Jake become two views of the same machine.', energyCost: 9, reward: { ending: 'merge', legacy: 2 } },
            { id: 'j5_burn_ledger', name: 'Burn the Ledger', unlockCopy: 'Destroy the numbers and let the myth survive.', energyCost: 7, reward: { ending: 'myth', marks: 4 } },
            { id: 'j5_rule_city', name: 'Rule the City', unlockCopy: 'If you can hold the machine, the machine becomes yours.', energyCost: 10, reward: { ending: 'rule', crew: 3 } },
          ],
        },
        upgrades: [
          { id: 'j_u_pockets', phase: 1, name: 'Deeper Pockets', cost: 20, currency: 'chips', unlockCopy: 'Carry more cash before it starts to matter.', reward: { carryCap: 25 } },
          { id: 'j_u_nerves', phase: 1, name: 'Steady Nerves', cost: 40, currency: 'chips', unlockCopy: 'Makes the first gamble sting less.', reward: { gambleStability: 1 } },
          { id: 'j_u_contacts', phase: 1, name: 'New Contacts', cost: 60, currency: 'chips', unlockCopy: 'Turns small favors into repeatable income.', reward: { reputationMult: 1.1 } },
          { id: 'j_u_risk', phase: 2, name: 'Measured Risk', cost: 120, currency: 'chips', unlockCopy: 'The table starts paying attention to the math.', reward: { gambleMultiplier: 1.15 } },
          { id: 'j_u_table_sense', phase: 2, name: 'Table Sense', cost: 180, currency: 'chips', unlockCopy: 'Lets Jake read momentum at blackjack and dice tables.', reward: { tableRead: 1 } },
          { id: 'j_u_crew_lead', phase: 2, name: 'Crew Lead', cost: 220, currency: 'chips', unlockCopy: 'Squads gain an extra slot in the autobattler.', reward: { squadSlots: 1 } },
          { id: 'j_u_double_down', phase: 2, name: 'Double Down', cost: 260, currency: 'chips', unlockCopy: 'Boosts high-risk gambling tiers.', reward: { highRollBonus: 1 } },
          { id: 'j_u_combat_notes', phase: 3, name: 'Combat Notes', cost: 380, currency: 'chips', unlockCopy: 'Adds passive buffs after every bracket win.', reward: { battlerRewardMult: 1.15 } },
          { id: 'j_u_watchful', phase: 3, name: 'Watchful Eye', cost: 500, currency: 'chips', unlockCopy: 'Lets Jake spot enemy traits before the fight starts.', reward: { encounterPreview: 1 } },
          { id: 'j_u_cashflow', phase: 3, name: 'Cash Flow', cost: 700, currency: 'chips', unlockCopy: 'Powers higher-stakes tables and faster hustles.', reward: { chipsPerMinute: 2 } },
          { id: 'j_u_network', phase: 3, name: 'Street Network', cost: 900, currency: 'chips', unlockCopy: 'Unlocks a second layer of side jobs and better payouts.', reward: { hustleTierBoost: 1 } },
          { id: 'j_u_ice', phase: 4, name: 'Cold Hands', cost: 1300, currency: 'chips', unlockCopy: 'Keeps the boss fights from rattling the crew.', reward: { critChance: 0.05 } },
          { id: 'j_u_kingmaker', phase: 4, name: 'Kingmaker', cost: 1800, currency: 'chips', unlockCopy: 'Upgrades all squad and table rewards in the back half.', reward: { globalRewardMult: 1.2 } },
          { id: 'j_u_final_bet', phase: 5, name: 'Final Bet', cost: 2500, currency: 'chips', unlockCopy: 'Makes the last branch materially different.', reward: { finaleChoiceBonus: 1 } },
          { id: 'j_u_legacy', phase: 5, name: 'Legacy Account', cost: 3200, currency: 'chips', unlockCopy: 'Carries some value into the next campaign if Jake becomes the bridge.', reward: { carryOver: 1 } },
        ],
        projects: [
          {
            id: 'j_p_1',
            phase: 2,
            unlockCopy: 'Choose whether Jake plays the odds or the people in the room.',
            options: [
              { id: 'j_p_1a', name: 'Play the Odds', effect: { gambleMult: 1.15, repMult: 0.95 } },
              { id: 'j_p_1b', name: 'Play the Room', effect: { reputationMult: 1.15, gambleMult: 0.95 } },
            ],
          },
          {
            id: 'j_p_2',
            phase: 3,
            unlockCopy: 'Decide whether the crew is built for speed or stability.',
            options: [
              { id: 'j_p_2a', name: 'Speed Crew', effect: { battleSpeed: 1.15, stability: 0.95 } },
              { id: 'j_p_2b', name: 'Anchor Crew', effect: { stability: 1.15, battleSpeed: 0.95 } },
            ],
          },
          {
            id: 'j_p_3',
            phase: 4,
            unlockCopy: 'Choose whether Jake runs the city quietly or loudly.',
            options: [
              { id: 'j_p_3a', name: 'Quiet Control', effect: { heatMult: 0.85, incomeMult: 0.95 } },
              { id: 'j_p_3b', name: 'Loud Empire', effect: { incomeMult: 1.15, heatMult: 1.1 } },
            ],
          },
          {
            id: 'j_p_4',
            phase: 5,
            unlockCopy: 'Pick the final story the city will tell about Jake.',
            options: [
              { id: 'j_p_4a', name: 'Disappear Clean', effect: { endingTone: 'vanish' } },
              { id: 'j_p_4b', name: 'Own the Myth', effect: { endingTone: 'myth' } },
            ],
          },
        ],
        thoughts: [
          { id: 'j_t_1', phase: 1, text: 'Jake knows the alley better than the main street. That is usually where the money hides.' },
          { id: 'j_t_2', phase: 1, text: 'Small bets are just social experiments with a tab attached.' },
          { id: 'j_t_3', phase: 1, text: 'If the city is paying attention, it is already late.' },
          { id: 'j_t_4', phase: 2, text: 'The table is a conversation where everyone lies with their chips.' },
          { id: 'j_t_5', phase: 2, text: 'A crew is just a business that can walk.' },
          { id: 'j_t_6', phase: 2, text: 'Jake is learning that automation is not laziness. It is leverage.' },
          { id: 'j_t_7', phase: 3, text: 'The autobattler feels like management with a visible scoreboard.' },
          { id: 'j_t_8', phase: 3, text: 'Winning once is luck. Winning with a roster is architecture.' },
          { id: 'j_t_9', phase: 3, text: 'Jake can tell when a team is about to fold. He can also tell when it is about to become dangerous.' },
          { id: 'j_t_10', phase: 4, text: 'The machine pays better when no one remembers where it started.' },
          { id: 'j_t_11', phase: 4, text: 'Every hustle becomes a supply chain if you stand still long enough.' },
          { id: 'j_t_12', phase: 5, text: 'Jake can either become the name under the lights or the story behind them.' },
        ],
        endings: [
          {
            id: 'j_end_1',
            name: 'Walk Away',
            unlockCopy: 'Jake leaves with enough to disappear and enough scars to matter.',
            result: 'The city keeps moving without him.',
          },
          {
            id: 'j_end_2',
            name: 'Take the Crown',
            unlockCopy: 'Jake takes the machine and lets the city call it progress.',
            result: 'The city has a new center of gravity.',
          },
          {
            id: 'j_end_3',
            name: 'Merge With Brian',
            unlockCopy: 'The stories converge and the save becomes a two-headed legend.',
            result: 'Brian and Jake continue as a shared myth.',
          },
        ],
        minigameHooks: [
          {
            id: 'jake_gambling_hook',
            system: 'gambling',
            unlockCopy: 'Jake can play every table once the backroom opens.',
            reward: 'Chips, marks, tickets, and rare comeback items.',
          },
          {
            id: 'jake_battler_hook',
            system: 'autobattler',
            unlockCopy: 'Jake can recruit a squad once the first crew contract lands.',
            reward: 'Loot, XP, roster upgrades, and bracket unlocks.',
          },
          {
            id: 'jake_hustle_hook',
            system: 'hustles',
            unlockCopy: 'Jake can chain side jobs into a repeatable income loop.',
            reward: 'Cash, reputation, and stable progression between major beats.',
          },
        ],
      },
    },
  };

  root.ACTIVITY_CONTENT = deepFreeze(ACTIVITY_CONTENT);
})(typeof window !== 'undefined' ? window : globalThis);
